spring:
  application:
    name: clear-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://192.168.0.16:3306/mydatabase?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: verysecret
  threads:
    virtual:
      enabled: true
